In [1]:
import pandas as pd

In [35]:
dl= pd.read_csv('./dl_logits.csv')
light= pd.read_csv('./lightgbm_logits.csv')

# print(dl['probs'].values)
# print(light.values)
prob_list= []
for i in range(len(dl)):
    tmp= list(map(float, dl['probs'].values[i][1:-1].split(',')))
    prob_list.append(tmp)

light_list= light.values
print(light_list)

[[0.52240994 0.18956558 0.14613629 0.14188818]
 [0.23079543 0.2994452  0.20696483 0.26279454]
 [0.1036028  0.33787529 0.21253159 0.34599033]
 ...
 [0.48706636 0.24146799 0.18973365 0.081732  ]
 [0.41378492 0.25357119 0.15466593 0.17797795]
 [0.5360509  0.23063704 0.14591899 0.08739306]]


In [42]:
import numpy as np

final_list= prob_list+ light_list
preds= np.argmax(final_list, axis= 1)
print(preds)

[[-1.39187536  0.45678176  1.57823123  0.8348277 ]
 [ 2.56683998  0.34348985 -0.98988738 -0.38912441]
 [ 0.46758905  1.43808345  0.58068868 -0.97910688]
 ...
 [-1.59297267  0.1540776   0.99784835  1.67091199]
 [-1.37494213  0.44594412  1.11062639  1.31827048]
 [-1.43903412  0.29016684  1.33814159  1.2250916 ]]
[2 0 1 ... 3 3 2]


In [47]:
test_label= pd.read_csv('./final_test_y.csv')['label'].values
test_label

array([3, 3, 3, ..., 0, 0, 0])